Tienda_FreeShop/Tienda_NetCore/Controllers/VentaController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;
using Tienda_NetCore.Models.Data;

namespace Tienda_NetCore.Controllers
{
    public class VentaController : Controller
    {
        private readonly TiendaContext _context;

        public VentaController(TiendaContext context)
        {
            _context = context;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var usuarioId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            if (string.IsNullOrEmpty(usuarioId))
            {
                return RedirectToAction("Login", "Cuenta");
            }

            var ventas = await _context.Ventas
                .Where(v => v.UsuarioId == usuarioId) // Filtrar por el usuario actual
                .ToListAsync();

            return View(ventas);
        }
    }
}

Tienda_FreeShop/Tienda_NetCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>@ViewData["Title"] FreeShop</title>
    <!-- Favicon-->
    <link rel="shortcut icon" href="https://firebasestorage.googleapis.com/v0/b/twecommerce-14b8f.appspot.com/o/Fotos_Perfil%2Ffree_shop_logo2.png?alt=media&token=862d4718-62f7-4ec5-a595-c0337d0d744d" />
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="~/css/site.css" rel="stylesheet" />

</head>
<body>
    <div class="content-wrapper">
        <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
            <div class="container px-4 px-lg-5">
                <!-- Logo -->
                <a class="navbar-brand" href="@Url.Action("Index", "Home")">
                    <img src="https://firebasestorage.googleapis.com/v0/b/twecommerce-14b8f.appspot.com/o/Fotos_Perfil%2Ffree_shop_logo.png?alt=media&token=f65cfffb-6915-4a2e-8325-5b22fe8ae70a" alt="Shop Logo" height="40">
                </a>
                <!-- Toggler button for mobile view -->
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">

                    </ul>
                    <div class="d-flex align-items-center ms-3">
                        <button id="carrito-btn" class="btn btn-outline-dark me-2" type="button">
                            <i class="bi-cart-fill me-1"></i>
                            Cart
                            <span id="carrito-cantidad" class="badge bg-dark text-white ms-1 rounded-pill">0</span>
                        </button>
                        <div class="dropdown">
                            <a class="btn dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                <i class="bi bi-person fs-4"></i>
                            </a>
                            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                <li><span class="dropdown-item-text">@User.Identity.Name</span></li>
                                <hr />
                                <li><a class="dropdown-item" href="@Url.Action("Index", "Venta")">Pedidos</a></li>
                                <li>
                                    <form asp-controller="Cuenta" asp-action="Logout" method="post" class="m-0">
                                        <button type="submit" class="dropdown-item">Logout</button>
                                    </form>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </nav>

        <main>
            @RenderBody()
        </main>
    </div>

    <!-- Footer-->
   
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>